[[ONNXRuntime]]
arch = "aarch64"
git-tree-sha1 = "b140b614d1b478dd9dbc9b37011b5277bfe27539"
lazy = true
os = "macos"

    [[ONNXRuntime.download]]
    sha256 = "dc9788dd1401bb338fa4984487107c0d6a4fef71a2879251f2527424414dc703"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.aarch64-apple-darwin.tar.gz"
[[ONNXRuntime]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "f79ad91f0a6b127538c98e1d7412a0fae53e5c48"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "03246bc18fe6ebd1945b64ea8308609645576a7d2c8b82e86c0182ee81f49099"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[ONNXRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e21156397e658abd1ef1f84672f4992bcbbaea5f"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "f1f8d38f3d344bbba2c9195cabe535c310f606e7cfc2b335f5575e655054a1a0"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11dd35eb9f3092cbb625b4cd1acf291324c081ef"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "d8b14bad04b03d4a87caf693f2f5aa3233aa72e6650818a0008109a0f7bc0662"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d35128a1b363803be87082fc30760b0be3ca2f35"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "67ae575c70a07f0569f305d9954c7019c5930fe6aebd2a6dae99fe2338242345"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5eeea6f13172388fc39cbcf78bb1f004ddcc7633"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "cbd049197484ef202248af1c97cf1b65b86951a13562b48f4c8e38514e4af0dd"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74e55ea23cf6962aeded9200e691ad889fe0d61e"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "94e2217d25f113ebccf38b87db4498c27e82bdbaac06052071466dde585a32ef"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3914003e5da67a2fb867ecbdab2686f3b1ffb95"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "ddd99209aff5e3689c1ff7bbd7bba297ac126aef7d75b58ae36db8d9cf8e8a16"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "i686"
git-tree-sha1 = "85e6418305745e90058426bf983ac70478d49317"
lazy = true
os = "windows"

    [[ONNXRuntime.download]]
    sha256 = "9fb12acdb90dfb4d58158058a213a448caed31a8abc22fa7f5a2d688855caadd"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.i686-w64-mingw32.tar.gz"
[[ONNXRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d70f85fa5ae23d98e2a2d8273800c3058307e6d3"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "db47844f613ecda02118c195353abbcb1a27af2f9d89619b50838dcc784198ec"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f51ab873dca8d80e854637090c8a3df92df3519a"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "2b6e8f19ac82c72d9f798a82d61cecd979351d04f67715a01ed05bad3adf5c45"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
git-tree-sha1 = "47b5f628d4a688c4ebaf2cb449026e2b28bbbd8e"
lazy = true
os = "macos"

    [[ONNXRuntime.download]]
    sha256 = "a208a315fab85991573563006d989903c0d23b1742c2adc80ed338952d66e57b"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.x86_64-apple-darwin.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "fb1100d0a6a0a36b79f98b245e970ac598796bf9"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "ce8395b7b5ddc6ecbbcedf3393188b62dea26809b331786b9ad396b06f03749e"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2934f5f7446b843d2d328f7973cd37809db45434"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "83eb3471b10bf20dd730d2f4ab47390433e84711ae28a31c4d69f3c2270285bd"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2787e84b3ff3af712b3159a7e610244e9693f9fa"
lazy = true
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "551426a0a94ec5d90da0950df164367adb7a56f285809564400174feb39d5791"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
git-tree-sha1 = "7cdfcc20760c8c00af26f4163a0fd0955b16dfdd"
lazy = true
os = "windows"

    [[ONNXRuntime.download]]
    sha256 = "7e7da0a23a66f8c043394209e719d9f9f80e462a68d90e92fa8a97005cf6a3a9"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.x86_64-w64-mingw32.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "8fa55028aeb49beca77fc8cf9dbc79f4f7ef97d5"
lazy = true
os = "windows"

    [[ONNXRuntime.download]]
    sha256 = "92e29b08c272e8a39e29d6265c4f7c422ff2e12b69f1cd898ab5cbe457ee80cd"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+1/ONNXRuntime.v1.10.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
