[[ONNXRuntime]]
arch = "aarch64"
git-tree-sha1 = "3879fefc8c2523c5b7e2d2cee751067e8d33db16"
os = "macos"

    [[ONNXRuntime.download]]
    sha256 = "5815b79aca3ed1158e49a2df2022707e2835582cf350fea84ea78276e24207e6"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.aarch64-apple-darwin.tar.gz"
[[ONNXRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39c53de69429912ff30da89457d96e39fc9f6f12"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "d4e252c4eb639d7e1e3dd929709fbe79e138aa4164f055ff56bc16feb3dc6dfb"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9c8732074b3625401fd4cf012d98926bd2791d2"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "4e90672d8f40c5f9b1db78a28a0551955c6fda95d88c7084b2aca3a311122dc0"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca77c6551defaa9a2c9b14f343952f803c8ed09c"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "623dc3a71638436d1d67e968ce433b5e30cf8ffa741b216e0f1d0778b2c7b907"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55264da8b57e81a52bd305498d47c3020ba71fe4"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "d3bae13d383dab37d5bd8e2c0dbc3d08198e51cb86952f22ad6a8963c140b6e9"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06f7fdc5493123cb3c45a53b4843cedb6a51eb4c"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "5b0660a40e7d4477df2c46c5ba8a3317a380242afa4ea35b3aeca29214aa1afe"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b7d4b8830099e56b6a04d5a0c830e72aa696316"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "aead934698b904104545aa01a99abd4f04faeb64e26b6e81e74c3b078aa81712"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "i686"
git-tree-sha1 = "97d3de3c35d9f61a6d0ad6d4b80a7a623951f5ff"
os = "windows"

    [[ONNXRuntime.download]]
    sha256 = "94f6da15c142a82d2643331a0f68ce4436eee8613f93cf776a88e050d000746d"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.i686-w64-mingw32.tar.gz"
[[ONNXRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d2f724c251ab8880e83a0306f6002a313952283"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "ebe8460406f9594006d0b007c010503ba19bd583aa79741601c281b566e9a735"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fdaaf680ba0d28aa6b41e024701e36911be2fd8"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "006c419b6d29906c5d568fcdd7eede2c2041bbfc074d19a9da956caf12001fae"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
git-tree-sha1 = "309b74fb7e9bc79f5452ebec45457f8118378e4c"
os = "macos"

    [[ONNXRuntime.download]]
    sha256 = "2c03fb8e6f93e1cf158cbc99356a3e96a5cae4c3e1da913dc8fe1f8366ff1587"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.x86_64-apple-darwin.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "312109e9dc02a722ad83a8f86a191eaf03dafb9c"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "faa22f8fc4214b71c5ed08ccab2b0c10112565ddb4dc60ea970029ac4b6ca557"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85f0d03b195a3c5d1a9b8042a09844cfaf3b2cec"
libc = "glibc"
os = "linux"

    [[ONNXRuntime.download]]
    sha256 = "15f7e484428e8e578c23b4fa16fcd071ddb411ec619e47e60cfd1e5840b545d3"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ONNXRuntime]]
arch = "x86_64"
git-tree-sha1 = "25373f89a8a6649f237fc11d6a4661df6add8dab"
os = "windows"

    [[ONNXRuntime.download]]
    sha256 = "d7881e1b4a886afa0cf2756eb5f8da52e2b5ce2b7a15ff7a2b8e358d95981c5e"
    url = "https://github.com/JuliaBinaryWrappers/ONNXRuntime_jll.jl/releases/download/ONNXRuntime-v1.10.0+2/ONNXRuntime.v1.10.0.x86_64-w64-mingw32.tar.gz"
